### PR TITLE
Fix Constructor bug for Student class

### LINKED ISSUE #117: Student Constructor bug
Bug when instantiating new student list

### PR DESCRIPTION
**Pull request by emmannyyy**
Fixes #117

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedStudent.java [hunk 1]
```diff
@@ -104,9 +104,13 @@ public Student toModelType() throws IllegalValueException {
         }
         final Email modelEmail = new Email(email);
         final Set<Tag> modelTags = new HashSet<>(studentTags);
-        Student student = new Student(modelName, modelPhone, modelEmail, modelTags, remark);
-
 
+        Student student;
+        if (remark == null) {
+            student = new Student(modelName, modelPhone, modelEmail, modelTags);
```
Comment (avrilmohh) [inline src/main/java/seedu/address/storage/JsonAdaptedStudent.java:110]: Looks good! Thanks for fixing it
